global:
  scrape_interval: 15s
  evaluation_interval: 15s
  
scrape_configs:
  - job_name: "node_exporter"
    static_configs:
      - targets:
        - 10.0.0.13:9100
        - 10.0.0.6:9100
        - 10.0.0.20:9100
        - 10.0.0.10:9100

  - job_name: "mysql_exporter"
    static_configs:
      - targets:
        - 10.0.0.20:9105
        - 10.0.0.20:9104  

  - job_name: "apache_exporter"
    static_configs:
      - targets:
        - 10.0.0.13:9117
        - 10.0.0.6:9117 

rule_files:
  - 'alert.rules'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: [ '10.0.0.10:9093' ]
